version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    env_file:
      - ../.env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=sqlite:////data/ridss.db
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - backend_data:/data

  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.web
      args:
        - VITE_API_BASE=/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    restart: unless-stopped

volumes:
  backend_data:

networks:
  default:
    name: ridss_net
